### ISSUE TITLE
Alterações quebraram o layout

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#12]
As alterações realizadas na issue #2 deixou o layout um pouco errado (aparece uma faixa branca abaixo do rodapé), ver em: http://cfp.phpsc.com.br/venue

**Comment by kassner** [comment]
Interessante. Tem 7px sobrando em baixo. Se mudar o margin-top ou o heigth via Firebug corrige, mas se colocar no arquivo, os 7px voltam. Ainda bem que eu não ganho a vida mexendo com CSS.
