### ISSUE TITLE
Termo de sigilo das informações

### ISSUE THREAD

**Issue by kassner** [PHPSC/phpsc-conf#15]
A frase está confusa: "O PHPSC manterá sigilo absoluto a respeito das informações pessoais dos participantes do evento para o grupo e patrocinadores do evento, divulgando publicamente apenas os números de participantes inscritos e os resultados do evento".

Devemos deixar mais claro que não iremos divulgar os dados pessoais para ninguém.

**Comment by lcobucci** [comment]
Foi colocado assim devido à existir uma remota possibilidade de tal fato acontecer, como não haviamos decidido/conversado sobre isso.

Agora que conversamos podemos alterar.
