### ISSUE TITLE
Atualizar conteúdo estático (do ano passado)

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#25]

**Comment by mingomax** [comment]
@wcomnisky @lcobucci Podem me passar os textos? Como estou mexendo nos layouts posso fazer esta issue também.

**Comment by lcobucci** [comment]
o @wcomnisky tinha ficado de rever essa parte... deixa do jeito que está o que você não conseguir "adivinhar" que mais tarde eu vejo.

**Comment by lcobucci** [comment]
Fechado com commit 76241b2bfd3884f542dc1a7455d8132051058a43
