### ISSUE TITLE
Permitir o cadastro de apoiadores

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#46]
Após a alteração solicitada na #39, permitir que os administradores do sistema cadastrem os apoiadores do evento.

O que precisamos fazer:
- Criar entidade Empresa
  - Nome
  - CNPJ
  - Email de contato
  - Telefone de contato (opcional)
  - Site
  - Logotipo (PNG transparente em alta resolução)
  - Twitter (opcional)
  - Fan page no facebook (opcional)
- Criar entidade Apoiador
  - Empresa
  - Evento
  - Detalhes (texto sobre oq o apoiador está oferecendo)

**Comment by lcobucci** [comment]
Alguém tem algo a adicionar @wcomnisky @djhonyy @kassner @mrprompt @mingomax @marcelaraujo ?

**Comment by djhonyy** [comment]
Posso sugerir o twitter e a página do facebook?

**Comment by lcobucci** [comment]
Massa @djhonyy!
