### ISSUE TITLE
Criar página de contato

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#6]
Precisamos criar a página de contato do site.

Imagino que esta tenha duas informações: formulário para o visitante enviar um email para a organização e os dados de contatos básicos da organização para aqueles que não estão afim de enviar o email (nome do twitter, página no facebook).

Para o formulário acredito que precisaríamos de nome, email, usuário do twitter (opcional) e mensagem. Lembrando que para usuários que já estão logados os campos nome, email e usuário do twitter podem ser preenchidos automaticamente.

**Comment by paruckerr** [comment]
Quais os dados que você quer passar ? nome / email / mensagem / telefone...algo mais ?

**Comment by kassner** [comment]
Acredito que nome, e-mail e Twitter seja o suficiente. Caberia aos membros da organização liberar o telefone pra algum membro caso seja preciso.

**Comment by kassner** [comment]
Isso é informação do usuário. Pelo que eu entendi da issue, é para qualquer membro entrar em contato com a organização do evento.

**Comment by lcobucci** [comment]
Na real o cara que criou a issue é um cabeçudo e falou de uma forma que pode ficar confusa.
Vou editar a parada.

**Comment by kassner** [comment]
Querendo ou não seria importante um formulário de contato que direciona a mensagem pra algum lugar (email, facebook?).

**Comment by lcobucci** [comment]
Issue removida, pois será feito um novo roadmap.
