### ISSUE TITLE
Utilizar o tipo "json_array" no mapeamento das tags de uma palestra

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#62]
Na entidade Talk existe um atributo chamado tags. Ele está mapeado como string, mas seria muito melhor se ele fosse um array.

O doctrine permite a utilização de um array (armazenando ele como json ou serializado). Para este caso o json_array seria uma solução muito boa.

**Comment by lcobucci** [comment]
O único problema aqui é o que já existe no db...

**Comment by kassner** [comment]
Era bom fazer uma Migration pra atualizar os dados, não?

Ping @lcobucci

**Comment by lcobucci** [comment]
Com certeza é bom pensar no script de migração
Em 23/02/2014 23:12, "Rafael Kassner" notifications@github.com escreveu:
