### ISSUE TITLE
Instação de projeto 

### ISSUE THREAD

**Issue by RAFAELGITHUB123** [PHPSC/phpsc-conf#66]
Boa noite,
Estou tentando instala o projeto para contribuir, pois me deparei com o seguinte problema na etapa : doc/inserts.sql (alterar schema no sql), acredito que seja para configurar o banco, pois dentro do arquivo inserts.sql tem apenas inserts e não tem o sql para criação do banco e das tabelas, e se eu estiver errado por favor me desculpe e me oriente da forma correta.
Desde já obrigado !

**Comment by kassner** [comment]
Você pode utilizar o comando `./vendor/bin/doctrine orm:schema-tool:update --dump-sql` para obter o sql de criação da estrutura. Acredito que seria mais interessante trocar esse inserts.sql por DataFixtures, o que achas @lcobucci?

**Comment by lcobucci** [comment]
Não só pode utilizar o comando, como deve :D
Se você ler a página https://github.com/PHPSC/phpsc-conf/blob/develop/CONTRIBUTING.md#cria%C3%A7%C3%A3o-do-banco-de-dados você verá as instruções de instalação.

Realmente @kassner, usar fixtures é o caminho ideal.
