### ISSUE TITLE
Sugerir o envio de tweet sobre participação no call for papers

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#7]
Possibilitar ao palestrante que submeteu as palestras o compartilhamento via twitter (postar um tweet dizendo o número de palestras que o usuário submeteu e convidando outras pessoas a fazer o mesmo).

**Comment by kassner** [comment]
Imagina algum template pra essa mensagem?

**Comment by lcobucci** [comment]
Sei lá... Algo como "Estou colaborando na #phpscConf com X trabalhos, contribua você também através do site http://cfp.phpsc.com.br! via @PHP_SC"

Claro que é só uma sugestão para o domínio tb...

**Comment by djhonyy** [comment]
Lembro que comentamos a respeito dessa opção lá no phpinga. Podemos colocar também algo quando a palestra for aprovada e até mesmo quando o participante for se inscrever.
