### ISSUE TITLE
Organizar o container de injeção de dependências para facilitar o modo de desenvolvimento

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#70]
Para facilitar a colaboração precisamos ter uma forma fácil de trabalhar com o ambiente de desenvolvimento. Hoje existem duas coisas que dificultam:
1. A autenticação é realizada via OAuth 2 nos providers, e não temos nenhuma forma para testar sem utilizar os dados de produção
2. A aplicação envia emails utilizando um servidor SMTP, assim cada colaborador precisa definir o servidor utilizando dados aleatórios

Para resolver o primeiro item podemos criar uma aplicação de teste, já o segundo podemos utilizar o NullTransport do SwiftMailer.

**Comment by lcobucci** [comment]
Penso que podemos criar um parâmetro que define o modo de execução do sistema, algo como `app.devmode`.

Se estiver em modo de desenvolvimento o sistema utiliza ArrayCache como driver, permite a geração automática de proxies do doctrine e usa o NullTransport. Quando não estiver ele utiliza APC/memcached cache, não gera proxy automaticamente e usa o SmtpTransport

**Comment by yourwebmaker** [comment]
Não seria melhor usa o appKernel do SF2 para isso?

**Comment by lcobucci** [comment]
Colocar o appKernel no meio do que utilizamos será um tiro no pé, e não ajudará muito
