### ISSUE TITLE
Informações sobre local

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#75]
Precisamos das informações sobre a universidade e a cidade para apresentarmos na página /venue.
- [x] Latitude/longitude e endereço
- [x] Como chegar na universidade
- [x] Hotéis
- [x] Restaurantes próximos

**Comment by eminetto** [comment]
_Latitude/longitude e endereço_

R. Paulo Malschitzki, 10 - Zona Industrial Norte
Auditorio Bloco da Reitoria

**Comment by eminetto** [comment]
_Como chegar na universidade_

https://www.google.com.br/maps/place/Rua+Paulo+Malschitzki,+264+-+Zona+Industrial+Norte/@-26.2520835,-48.8542012,17z/data=!3m1!4b1!4m2!3m1!1s0x94deafa464ae81eb:0xdf8f7166188de11d

O bom é que tem linhas de busão indo pra universidade o dia todo

http://www.gidion.com.br/horarios-e-itinerarios/

Para quem tem Android existe um app que ajuda a localizar as linhas de ônibus:

https://play.google.com/store/apps/details?id=com.pegabuzz&hl=pt_BR

**Comment by eminetto** [comment]
_Hotéis_

Os mais próximos são:

http://www.hotelplazanorte.com.br/
http://www.hotel10.com.br/cidades/joinville

**Comment by eminetto** [comment]
_Restaurantes_

Tem um restaurante dentro do campus:
http://www.manarefeicoes.com.br/index.php?pg=abass

E do lado da universidade tem o maior shopping de Joinville, o Garten com diversas opções 
http://www.joinvillegartenshopping.com.br/gastronomia/

**Comment by lcobucci** [comment]
Latitude e longitude: -26.251720,-48.854591
