### ISSUE TITLE
Remover campo ENUM do mapeamento

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/phpsc-conf#77]
A entidade `Talk` possui um atributo chamado `complexity` que está mapeado como ENUM.

Como o ENUM não é um tipo comum em todos os SGDB relacionais, o Doctrine não implementa ele por padrão e ao invés de criar um tipo do Doctrine foi mapeado no column definition. Dessa forma TODA vez que roda o comando `doctrine orm:schema-tool:update` o Doctrine encara como uma alteração.

No setter tem as devidas validações, portanto devemos alterar esse cara para string length = 1 (solução mais fácil, rápida e indolor).

**Comment by yourwebmaker** [comment]
Dica.... Rolava de usar o SplEnum =)

**Comment by lcobucci** [comment]
Não temos como instalar a extensão :-(
