### ISSUE TITLE
Erro 404 em URL de imagem

### ISSUE THREAD

**Issue by kassner** [PHPSC/phpsc-conf#82]
https://github.com/PHPSC/phpsc-conf/blob/b1bcb4e56c5bde581c8c19c5e4adb6d9d8b23ce4/src/PHPSC/Conference/Application/Action/Event.php#L15

Devido a isso, se for acessado o link direto da imagem no navegador (/event/3?w=180&h=170 por exemplo), é retornado um 404. Acredito que se a imagem tivesse sua rota específica (/event/{id}.{format} por exemplo, sem a obrigatoriedade do accept), seria mais fácil de tratar isso, além de que permitiria um melhor controle de cache por parte do webserver.

**Comment by lcobucci** [comment]
Até onde conheço o webserver utilizar os headers para realizar o cache, portanto isso não influencia.

O objetivo é dar erro 404 mesmo, pois a representação em HTML/XML/\* deste recurso não existe.

Utilizar o formato na URI não é uma boa prática na construção de aplicações web, pois fere a especificação do protocolo HTTP.

**Comment by kassner** [comment]
> Utilizar o formato na URI não é uma boa prática na construção de aplicações web, pois fere a especificação do protocolo HTTP.

De que forma uma URI tipo `/event/3.jpg` vai contra a especificação?

> Até onde conheço o webserver utilizar os headers para realizar o cache, portanto isso não influencia.

É mais fácil pra configurar, uma vez que eu mando todas as URLs que tem a extensão .jpg serem cacheadas. Se eu utilizar o content-type, todos os requests vão ter que ser verificados pra ver se podem ser cacheados ou não.

> O objetivo é dar erro 404 mesmo, pois a representação em HTML/XML/\* deste recurso não existe.

Você está certo, porém, no meu caso, meu Accept header é: `Accept:  text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. Esse header pode aceitar qualquer outra coisa, caso não tenha um HTML/XML pra ser respondido. Por que não a imagem?

**Comment by lcobucci** [comment]
Vai contra a especificação pois o recurso é `/event/3`, a URI `/event/3.jpg` aponta pra outro recurso. O formato de representação deles varia de acordo com o Accept.

Agora quando o Accept possui */* a brincadeira muda e você está correto :smile:.

**Comment by lcobucci** [comment]
Informação importante... a aplicação já envia os headers de caching ;-)

https://github.com/PHPSC/phpsc-conf/blob/develop/src/PHPSC/Conference/Application/Service/ImageRenderingService.php#L60
