### ISSUE TITLE
Bug na página de trabalhos submetidos

### ISSUE THREAD

**Issue by drgomesp** [PHPSC/phpsc-conf#85]
Galera, acabei de encontrar este bug:

![captura de tela 2014-06-02 as 09 50 28](https://cloud.githubusercontent.com/assets/696982/3147270/886a2f50-ea54-11e3-87c1-358b46d3e67e.png)

Mais tarde, vou dar uma olhada pra ver onde pode estar acontecendo.

**Comment by kassner** [comment]
Falha minha em deixar os erros ativos no servidor, já desabilitei.

@drgomesp podes testar de novo pra ver se os erros ainda aparecem?

**Comment by drgomesp** [comment]
@kassner os erros já não estão mais aparecendo, porém o bug ainda existe, certo?

**Comment by kassner** [comment]
@drgomesp isso

**Comment by lcobucci** [comment]
:smile: e falha nossa de codar a parada com erro haiuhauiahui

vlw @drgomesp  e @kassner, vou olhar aqui

**Comment by lcobucci** [comment]
O problema está aqui: https://github.com/PHPSC/phpsc-conf/blob/develop/ui/PHPSC/Conference/UI/Pages/Call4Papers/FeedbackItem.phtml#L16

Não precisa mais desse explode(), vou trocar.

**Comment by drgomesp** [comment]
:+1:
