### ISSUE TITLE
PHPSC Conf 2016

### ISSUE THREAD

**Issue by eminetto** [PHPSC/phpsc-conf#88]
Tomei a liberdade de criar essa issue para abrir a discussão quanto a edição 2016 da Conf
Se esse não for o melhor formato/local me avisem que eu mudo. E já adianto as desculpas se for o caso :)

Minha proposta é fazermos o evento em Joinville em Abril ou Maio. Acho que Maio é até melhor
Sugiro também um cronograma:

Definição da cidade: Novembro
Definição da data e local: Dezembro
Início da divulgação: Dezembro
Início da procura por patrocinadores: Janeiro
Call for papers: Janeiro e Fevereiro
Aprovação das palestras: Março

O que acham?

**Comment by mrprompt** [comment]
De acordo

**Comment by djhonyy** [comment]
Concordo com o Elton.

**Comment by venturacodes** [comment]
Concordo tambem

**Comment by eminetto** [comment]
Coloquei um milestone para definirmos até a próxima sexta :)
Quem estiver a favor dá um :+1:  (fora o pessoal q já se manifestou a favor hehe)

**Comment by iagoEffting** [comment]
:+1:

**Comment by wcomnisky** [comment]
Acho que o Trello tem mais features pra tratar disso..

**Comment by cassiosantos** [comment]
:+1:

**Comment by mrprompt** [comment]
@wcomnisky concordo contigo, mas acho que se deixarmos as coisas aqui no Github, torna-se mais "colaborativo" (eu to muito chato com isso).

**Comment by mingomax** [comment]
@wcomnisky O trello a gente usa para coisas mais internas,  acho essa proposta do @eminetto usar aqui válida pois também é uma forma de darmos transparencia para certas decisões que a comunidade toma.

**Comment by sergiors** [comment]
:+1: 

@eminetto a liberação a grade seria logo após fechar o c4p, ou teria um tempo de aprovação?
Pois em evento que envolve R$ eu sempre analiso a grade antes de comprar, indiferente do lote

**Comment by eminetto** [comment]
@sergiors faríamos a liberação da grade o quanto antes. Pra quem vai palestrar se organizar e pra quem vai comprar tmb. Eu tmb não gosto de eventos que deixam td mundo no suspense até o último momento hehe

**Comment by lcobucci** [comment]
Eu concordo com o @wcomnisky, o trello tem mais recursos. E dá pra se ter uma board pública pra essas paradas. Se quiserem manter no github eu sugiro colocar em outro repo, pra não misturar com as coisas desse sistema que montei.

Quanto à proposta eu acho arriscada a questão do patrocínio, as empresas fazem o planejamento finaceiro do ano que vem agora. A gente sempre perde patrocínio em função disso.

Sugiro:

Definição da cidade: Novembro
Definição da data e local: Novembro
Início da divulgação: Dezembro
Início da procura por patrocinadores: Dezembro
Call for papers: Janeiro e Fevereiro
Aprovação das palestras: Março

Gosto de Joinville, por ser no "começo" do estado é de fácil acesso para o povo do Paraná e quem tá pra cima, porém - por mais que role um stress fudido - acho boa a ideia de ser itinerante. Tem pessoas de SC que não conseguem se deslocar tão facilmente e IMHO a gente deveria priorizar o povo de SC.

**Comment by eminetto** [comment]
Legal @lcobucci, concordo com a mudança das datas. Quanto a continuar itinerante podemos conversar em outro momento. Eu tmb gosto da ideia mas tem gerado uns problemas de organização sempre :)

**Comment by lcobucci** [comment]
Yes indeed :smile:
